volumes:
  mongo_data_folder:
networks:
  uber-user-ms:
services:
  
  mongo-container:
    image: mongo:4.4
    ports: 
      - 27017:27017
    networks:
      - uber-user-ms
    volumes:
      - mongo_data_folder:/data/db
  node-app:
    image: titik002/uber-clone-user-service:latest
    ports:
      - 4001:4001
    networks:
      - uber-user-ms
    depends_on:
      - mongo-container
    environment:
      - DB_URL=mongodb://mongo-container:27017/user-service