

networks:
  uber-ms-network:
    driver: bridge

volumes:
  mongo_data_folder_user:
  mongo_data_folder_captain:
  mongo_data_folder_ride:

services:
  # User Service
  mongo-container-user:
    image: mongo:4.4
    
    networks:
      - uber-ms-network
    volumes:
      - mongo_data_folder_user:/data/db

  user-service:
    image: titik002/uber-clone-user-service:latest
    ports:
      - 4001:4001
      - 9231:9231
    networks:
      - uber-ms-network
    depends_on:
      - mongo-container-user
    environment:
      - DB_URL=mongodb://mongo-container-user:27017/user-service

  # Captain Service
  mongo-container-captain:
    image: mongo:4.4
     
    networks:
      - uber-ms-network
    volumes:
      - mongo_data_folder_captain:/data/db

  captain-service:
    image: titik002/uber-clone-captain-service:latest
    ports:
      - 4002:4002
      - 4005:4005
      - 9232:9232
      - 9234:9234
    networks:
      - uber-ms-network
    depends_on:
      - mongo-container-captain
    environment:
      - DB_URL=mongodb://mongo-container-captain:27017/captain-service

  # Ride Service
  mongo-container-ride:
    image: mongo:4.4
    
    networks:
      - uber-ms-network
    volumes:
      - mongo_data_folder_ride:/data/db

  ride-service:
    image: titik002/uber-clone-ride-service:latest
    ports:
      - 4003:4003
      - 9233:9233
    networks:
      - uber-ms-network
    depends_on:
      - mongo-container-ride
    environment:
      - DB_URL=mongodb://mongo-container-ride:27017/ride-service
      - USER_SERVICE_URL=http://user-service:4001/users  # Use service name here
