volumes:
  mongo_data_folder_ride:
networks:
  uber-ride-ms:
services:
  
  mongo-container-ride:
    image: mongo:4.4
    ports: 
      - 27019:27017
      - 6003:9229
    networks:
      - uber-ride-ms
    volumes:
      - mongo_data_folder_ride:/data/db
  node-app:
    image: titik002/uber-clone-ride-service:latest
    ports:
      - 4003:4003
    networks:
      - uber-ride-ms
    depends_on:
      - mongo-container-ride
    environment:
      - DB_URL=mongodb://mongo-container-ride:27017/ride-service