volumes:
  mongo_data_folder:
networks:
  uber-user-ms:
services:
  
  mongo-container-user:
    image: mongo:4.4
    ports: 
      - 27017:27017
      - 6000:9229
    networks:
      - uber-user-ms
    volumes:
      - mongo_data_folder:/data/db
  node-app:
    image: titik002/uber-clone-user-service:latest
    ports:
      - 4001:4001
    networks:
      - uber-user-ms
    depends_on:
      - mongo-container-user
    environment:
      - DB_URL=mongodb://mongo-container-user:27017/user-service